### ISSUE TITLE
No Std Compatibility

### ISSUE THREAD

**Issue by domenukk** [VFLashM/tuple_list#1]
Since this trait is mainly a macro, it should be easy to add `no_std` support.
Probably, adding `#![no_std]` to the first line of lib.rs would be enough.

**Comment by VFLashM** [comment]
Thank you for PR. Merged.

**Comment by domenukk** [comment]
Great! Can you push it on crates.io, too, please? Then I can use it instead of a github version. Thx :)

**Comment by VFLashM** [comment]
Done! Version 0.1.3 published. Thanks again.
